name: Luau and Lua Script Checker

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  filter-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find and Process Luau/Lua Files
        shell: bash
        run: |
          found_files=0
          
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            
            ext="${file##*.}"
            
            if [ "$ext" = "lua" ] || [ "$ext" = "luau" ]; then
              found_files=$((found_files + 1))
              
              temp_file=$(mktemp)
              echo "--[===========================================================[
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣿⣿⣿⣯⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡭⣿⣿⡿⣷⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡜⣷⣿⣿⢿⡸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣼⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢰⢫⣿⣿⢿⣘⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣽⣿⣿⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⢆⡫⢾⣿⡿⣌⠳⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡷⣿⣿⣿⣯⢿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣾⣿⣿⣽⣿⣿⣿⣿⣿⣿⣟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⡌⢖⡫⣿⣟⣇⠳⠼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣽⣿⣿⣿⢿⣾⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣿⢿⣾⣟⣿⣯⣿⣿⣿⣿⣯⢿⣿⣿⣿⣿⣿⣿⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣻⣿⣿⣿⣟⡜⠥⣞⢽⣿⢼⡹⡸⢽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣽⣿⣿⣿⣿⣿⣿⣿⣿⣟⣿⣿⣿⢽⣿⣿⣿⣻⣞⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣾⣟⣿⣟⣿⣾⢿⣻⣿⣿⣿⣿⡯⣿⣿⣿⣿⣿⣿⣿⢾⣿⣿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⣟⣯⣷⣿⣿⣿⣿⣿⣻⢌⡳⣽⡞⣿⡇⣿⢥⡛⣼⣿⣿⣿⣿⣝⡿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣟⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣿⣾⣻⢿⣿⣿⢼⣻⢿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣟⣾⢯⣿⢿⣻⣿⣿⣿⣿⣏⣷⣿⣿⣿⣿⣿⣻⢿⣿⡿⣽⣻⣿⣿⣿⣿⣿⣿⣿⢿⣻⣽⣾⣿⣿⡿⣟⣯⣿⣾⣿⣿⣽⠎⡖⣽⣿⡵⣿⠸⣷⣙⡖⣯⢿⣿⣿⣿⣿⣷⣮⣝⣻⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⢿⣿⣿⣿⣯⣿⣿⣿⣟⣿⣿⣽⣯⢿⣿⣯⢯⣿⡞⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢾⣿⣽⣟⣾⡿⣯⣟⣿⣿⣿⣿⣿⣳⢞⣿⣿⣿⣿⣽⣿⣻⣿⢿⣽⣻⣿⣿⣿⢿⣻⣵⣾⣿⣻⡿⣽⡿⣾⣟⡿⣯⡷⣯⢿⣿⣻⣜⡱⣫⣿⣷⢻⡇⢿⣷⢺⣥⢻⣿⣿⣿⡿⣟⣿⣿⣿⣿⣶⣭⣛⡿⣿⣿⣿⣿⣿⣿⣯⢿⣿⣿⣿⣽⣾⣿⣿⣯⣿⣿⡷⣏⣿⣿⣯⣏⣿⢿⣻⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡯⣿⣿⢾⡯⣷⢿⣻⣽⢾⣿⣿⡿⣿⢧⣻⡽⣟⣿⣿⣻⣯⢷⣿⣻⢞⡷⣯⣿⣾⢿⣯⡷⣿⢾⣽⣻⣽⣻⢷⣯⣟⣷⣻⣽⣻⣿⣿⢆⡳⢽⣻⣿⣯⣝⠮⣿⣿⡜⣷⣹⣿⣿⣟⣿⢿⣽⣾⣿⢿⣿⣿⣿⣶⢯⣻⢿⣿⣿⣯⣟⣿⣿⣿⣻⣞⣿⣿⣳⣿⣿⣻⣏⣷⣿⣷⣻⢼⡿⣽⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡗⣿⣿⣻⡽⣽⣻⣽⣞⣿⢿⣳⣿⡿⣟⢶⣻⡿⣿⣿⣻⣿⣻⡾⣽⢾⣻⢷⣿⢯⣟⡾⣽⢯⣟⣾⣳⢯⣟⣻⢾⣹⠾⣵⣻⢼⣻⣿⢧⡹⢞⣿⣿⣿⣎⡷⣹⣿⣞⣽⣧⡟⣿⡾⣟⣯⣿⣻⣾⢿⣻⣾⢿⣽⣿⣿⣿⣾⣽⣿⡞⣿⣿⣿⡽⣯⣿⡿⣽⣿⣿⣽⣻⢼⣿⡷⣻⢾⣿⡯⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣹⣿⣿⣹⢿⡷⣏⣷⢿⣾⣿⢿⣹⡿⣏⡾⣱⣿⢿⣿⣹⣷⣿⣹⣏⢿⣹⣾⣹⡿⣾⣹⣏⡿⣾⣇⣿⣹⠾⡉⠏⡷⢿⣱⢏⡷⣏⣿⣇⠿⣉⣿⣿⣿⣿⢷⣹⣿⣿⡾⣿⣹⢷⡿⣏⡿⣾⣹⣏⣿⣿⣹⣿⣏⣿⣷⣿⣏⣿⣿⣹⣏⣿⣷⣿⣏⣿⣿⣹⣿⣿⡾⣿⢾⣿⣿⢹⢷⣿⢿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣻⣿⡿⣽⢾⣝⣻⡼⣟⡾⣽⣟⣯⣿⢧⣝⣳⢯⣿⣿⣽⣷⣻⣽⣞⡯⣷⢫⣿⣟⠷⠛⠈⠉⠀⠉⠀⠉⠈⠙⠋⢹⢣⠟⣾⡱⣏⠿⣞⡽⣣⢿⣿⣿⣿⣿⢾⣯⣿⣿⣟⡟⡎⠑⠉⠘⠁⠉⠈⠑⠋⠛⠳⠿⣯⣷⡿⣾⣿⣿⣷⣹⣿⣟⡷⣯⣿⣯⢿⣿⣿⣽⣻⢞⣽⣿⣏⣯⢿⣻⣽⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢯⣿⣿⡟⣾⡟⣾⣱⢿⣽⢺⣽⢾⣻⢾⣓⡮⣝⣯⣿⣷⣻⣾⣟⡷⣯⡗⡯⢿⠟⠀⠀⠀⠀⠀⠀⠀⠰⣶⣷⣶⠀⠀⠉⡞⣥⢻⣜⡻⣜⡳⣭⢿⣿⣿⣿⣾⣿⣿⣾⢿⡝⠀⢠⠀⠀⠀⠀⠀ ⠀⠀ ⠀⠀ ⣀⣀⡈⠙⠿⣽⣷⣿⣗⢯⣿⡿⣽⣳⣿⣽⢺⣿⡿⣾⡽⣞⣿⣏⣷⢯⢾⣹⣿⡿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣿⡿⣽⣹⡽⣹⣧⢟⡾⣝⡾⣯⣟⣯⠧⣟⡜⣷⣯⣿⣽⣳⢿⣽⡧⠟⠀⢸⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠀⠀⣯⡔⠸⣼⣳⣾⣵⣯⣽⣣⣟⣿⣿⣿⣿⣿⣿⢯⡗⠌⣴⢧⠀⢀⠀⠀⠀⠀  ⠀⠀ ⠀⠛⠿⠃⡦⡀⠈⠟⡾⣽⣻⢾⣟⣷⣹⡿⣎⢿⣿⣻⢷⣻⡜⣿⣏⣿⡞⣯⢞⣿⣿⢿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡷⣿⣿⣻⣳⢿⡳⣿⣿⢫⣿⡜⡿⣵⡻⢾⣙⢮⣓⣟⡾⣿⣼⣟⣯⣷⡞⣅⠀⠼⢤⠠⠄⠀⢀⠀⢀⢀⡀⠀⠀⠀⢸⡟⣥⢻⡼⣷⡿⣿⣻⣿⡿⣿⣟⣯⣿⣾⣿⣿⢯⣞⡱⣬⢻⡄⠀⠈⢠⠀⠀⠀  ⠀⠀⠄⠀⢀⣿⡔⢀⣬⣑⡳⣝⣾⣟⡾⣱⣿⡍⣾⣿⢯⣟⡷⡭⣿⣯⣿⣯⢽⢾⣯⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣿⢽⣳⢯⣏⣷⣹⣿⡻⣞⡭⢿⣱⡟⣯⢞⣣⢯⣸⢿⣽⣞⣷⣻⣾⣿⡽⢀⠈⠻⢧⣀⣀⡄⣬⢤⣣⢦⢶⠶⣏⣿⣹⣞⣯⣟⣷⣿⣟⣿⣟⣿⣿⣿⢿⣿⡿⣿⣿⣿⣾⣟⣷⣯⣟⣷⡶⣦⣽⢧⣳⣌⣄⣀⣠⠎⣭⣀⢸⣿⣟⣿⣻⡼⣯⣗⣻⢧⡝⣶⣿⢿⡽⣞⡷⣹⣷⣿⣿⡞⣯⡷⣿⣻
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣳⣿⢞⣯⡟⡦⣽⢞⣿⡗⣯⡟⣭⢷⡻⡵⢎⣳⢳⡬⣟⣿⣞⣷⢯⣿⣿⣟⠤⢋⢾⣱⢻⡼⣹⢎⡷⣹⢎⣯⢻⡝⣶⢻⢮⡷⣻⣞⡷⣿⣽⣾⡿⣿⣾⣿⣟⣿⣿⡷⣿⣞⣯⢷⣻⣞⣷⣻⡽⣞⣯⢷⣻⠾⣽⣻⢞⣵⣯⢸⣿⡾⣟⣷⣻⡷⣹⣞⡏⣾⡱⣿⢯⡿⣽⣓⢿⡷⣿⣟⡯⣿⡗⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣽⣿⢺⣷⢻⣱⣯⢯⣻⡯⣷⢯⡽⣞⡵⢯⣙⡮⢧⣓⢯⣿⡾⣿⣹⣿⣿⣿⡘⠬⣞⡵⣫⢞⡵⢫⢞⣥⢻⣬⢳⡝⣮⢏⣷⢻⡵⣯⢿⣽⣾⣻⣽⣿⣯⣷⣿⣟⣾⣿⣳⣟⡾⣯⢷⣻⡼⣳⡽⣳⢞⡯⣞⡻⢧⣟⡻⣞⣿⢸⣿⣿⣟⣿⣼⡻⡵⣾⣙⠶⣝⡿⣯⣟⡷⣏⣾⣟⣿⣿⢽⣿⣻⡽⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣞⣿⣻⡾⢧⣿⣿⢞⣭⢳⢯⣷⣹⢞⡽⣳⢸⡝⣧⡹⢎⣿⣿⣿⢧⣿⣿⣿⡇⢚⡵⣫⢗⡹⣎⢻⡜⢦⡳⢎⣧⠻⣼⡹⣎⠿⣼⢯⣟⣾⣳⢿⣻⣾⢿⣟⣾⣯⣿⣾⣳⢯⣟⣭⢷⡳⣽⢣⣟⡵⣫⠾⣵⢫⡟⣼⢳⣻⣿⣸⣿⣿⣯⣟⣶⡻⣵⡻⢜⡻⣼⣹⢷⣻⣽⢷⣺⣯⢿⣿⣺⣿⣳⣿⣻
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢾⣽⡧⣟⣻⣿⣿⣞⣮⠟⣞⣧⣛⣮⢷⡱⢮⣽⢲⢭⡓⣯⣷⣿⡧⣿⣿⣿⢧⢙⡾⣱⣋⠷⣜⣣⢞⣣⡝⡞⣴⡛⡶⣝⡞⣯⣳⢟⣾⣳⢿⣻⣯⣟⡃⣿⣯⣷⡿⣿⣽⣻⡼⣏⡾⣵⢫⡿⣼⢳⣭⢻⡜⣧⢻⡵⣫⢷⡯⣿⣿⣿⣯⣿⢶⡻⣼⣛⠼⣓⢧⡝⣿⡽⣯⡷⣯⣿⢻⣿⣽⣿⣳⡷⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢻⣞⣷⢯⣿⣿⣿⣿⢺⣽⡹⣧⢻⡜⣧⠏⣾⢼⣋⢶⡙⢾⣿⣿⡗⣿⣿⣿⣏⠲⣝⢧⡝⣎⡳⣜⠧⣞⡼⣹⠖⣽⢳⡝⣾⣱⢯⣟⡾⣽⣻⣯⣷⣻⠰⣯⣷⡿⣽⣿⣳⢯⢷⣫⠷⣭⢷⣻⡷⣏⡞⣧⢻⡜⣧⢻⡵⣫⣟⣿⣿⣿⣿⣯⢷⣏⡷⣭⢚⡽⢮⡝⣷⢿⣯⡷⣟⣿⣹⢾⣿⣿⣹⣿⣽
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⡝⣾⣻⣿⣿⣿⣿⡯⣗⣳⢯⡗⣯⢞⡵⣋⡾⣏⢮⢇⣻⢚⣿⣿⡟⣼⣿⣿⣿⠸⣝⢮⡜⣮⢳⣭⣛⢶⡹⣵⢫⣗⣯⡽⣞⣭⣟⡾⣽⡿⣽⣷⣿⣳⣟⣷⣿⣽⣟⣾⢯⣟⣯⢷⣛⣧⡟⣾⡽⢧⣻⠼⣧⣛⡞⣧⣻⣽⣎⣿⣿⣿⣿⣯⢷⣞⡳⣏⢧⣛⢧⡻⣼⣟⣯⡿⣽⣿⣽⣿⣿⣿⢳⣿⣯
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣽⣳⢟⣷⣻⣿⣿⣿⢾⡽⣹⢺⣇⢯⢺⡵⢩⣗⡟⣮⣙⠦⡏⣿⣿⣏⣿⣿⣿⣿⡙⣮⣓⢾⡱⣟⡶⢯⣳⠿⣼⣻⣼⡞⣷⣻⢾⣽⣻⣽⣟⡿⣷⣻⢿⣻⢿⡾⣟⣾⣻⣟⡾⣽⢾⡽⣶⣻⣳⣻⢻⣼⢻⡶⢯⣝⡾⣵⣻⢸⣿⣿⣿⣿⣯⠿⣼⢱⣏⡶⢏⡾⣱⠽⣾⣿⡿⣽⣿⣿⣾⣿⣭⡿⣞⣷
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣟⣶⣿⢯⡷⣯⢿⣟⡾⢯⢞⣽⣹⢜⡎⣿⡘⢧⣻⣼⢣⢞⡣⢇⣿⣿⣧⢿⣿⣾⣿⣧⢳⡽⣾⣽⣻⣞⡿⣽⣻⢷⣻⡾⣽⣷⣻⣿⢾⣟⣿⡾⡹⠥⠎⠦⣍⠎⡙⢻⣽⢿⣯⣿⢯⡿⣽⣳⢯⣗⣯⣟⡾⣯⣟⢿⣜⢷⣻⠥⣟⣿⣿⣿⣿⣯⢟⡧⢻⣜⢧⢻⡵⣫⠗⣿⣷⣟⣯⣿⣿⣾⣿⢧⣟⣷⢻
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣾⣿⣿⣿⣻⡝⣾⡿⣽⢫⣟⡮⡟⣼⡸⢧⣙⢧⡷⣞⢭⠚⣤⢓⢾⣿⣯⢿⣿⣿⣯⡷⢩⢾⣿⣞⡷⣯⣿⢷⣟⣯⣷⣿⢿⣾⣿⣽⣿⡿⣯⠗⠁⠀⠀⠀ ⠀⠄⠀⠀⢯⢿⣿⣾⢿⣻⣽⢯⣟⣾⣳⢯⣟⡷⣯⣟⢮⣟⡷⢨⣿⣿⣿⣿⣿⣯⡟⡼⣳⢺⣭⠳⣿⣱⢻⡜⣿⣯⣟⣿⣿⣷⣿⢺⣯⣟⢿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡾⣽⣿⣿⣿⣿⣳⣿⢻⡽⢯⣟⡾⣇⣟⢶⣛⠧⣎⡳⡝⣎⢇⡻⣔⢫⢾⣿⣯⣿⣿⣿⣿⣿⡈⢎⢿⣟⡾⣷⣻⢿⣻⣯⣿⣿⡿⣿⣾⣿⢿⡿⠁⠀⠀⠀⠀⠀⠀ ⡀⠀⠀⠘⡘⣿⣽⣿⣿⣻⣟⡿⣾⡽⣿⣽⣻⢗⣯⠳⠞⡱⢺⣿⣿⣿⣿⣿⣳⢟⡰⢧⣛⣧⢻⡽⣧⢳⣍⢿⣽⣯⣿⣿⣯⣿⢻⡾⣽⢾
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣿⣿⣿⣿⣿⣿⣻⣼⢿⡽⣟⣯⣽⣺⢮⡿⡍⢞⡰⢵⡹⡜⢮⡱⢎⡳⣜⣿⡷⣿⣿⣿⣿⣿⡱⢊⡜⢻⡷⣹⡽⣻⣟⣿⣽⣿⣿⢿⣿⣾⣿⡏⡀⣠⣴⣤⡔⣀⡀⣤⣤⣄⠀⣇⢻⣿⣿⣾⢿⣽⣻⢷⣿⣻⠾⣝⠾⡌⢣⠜⣡⣿⣿⣿⣟⣿⣿⡽⣎⠵⣣⠞⣽⡎⣷⢯⡗⣮⢝⣿⣞⣯⣿⣿⣿⣹⢯⣟⡞
⣿⣿⣿⣿⣿⣿⣿⣿⣿⢷⣻⣿⣿⣿⢿⣯⣷⣿⡽⣯⢿⣻⢾⡵⠯⢏⣵⢺⣍⢾⡱⢧⣛⢶⡹⢮⡱⢎⣿⣟⣿⣿⣿⣟⣿⣇⠣⡜⡡⢟⡰⢏⢿⡾⣽⢾⣿⣾⢿⣟⣿⣾⠁⣿⣿⣿⣟⡾⡱⢟⡷⢊⠿⣷⣯⢾⣿⢷⡿⣯⣟⣯⣟⡾⢭⡛⡌⢣⠜⣡⠎⣥⣿⣿⣯⣿⢯⣿⢞⡬⢳⢥⢛⡲⣝⠮⣿⣽⣚⠮⣽⡾⣟⣿⣿⣯⢟⣟⡾⣝
⣿⣿⣿⣿⣿⣿⣿⣿⣏⣿⣿⢿⡽⣯⣿⣿⣿⣿⢿⣻⣯⢟⣫⣴⣿⣻⣼⢷⣞⣯⣽⣳⢯⡾⣝⣧⣛⠧⣿⣯⣿⣿⣿⣿⣺⣧⢛⡴⣉⢎⠲⣌⠣⠟⣭⢟⣿⣯⣟⡾⣿⣽⡘⣿⢿⣿⢿⡡⢓⡌⡖⣩⢂⠽⣟⢾⡽⣯⢟⡳⣿⡟⡼⠱⢋⠴⡘⡥⢚⠥⣚⢴⣿⣿⣳⢿⣻⣟⠮⣜⢣⢎⢧⠳⣬⠳⣝⡾⣭⢻⡜⣻⣟⣿⣿⣿⣻⢾⡽⣏
⣿⣿⣿⣿⣿⣿⣿⣿⣽⣻⣵⣿⣿⣿⣿⣿⡿⣿⣯⣛⣴⡿⣟⣷⣿⣿⣿⣿⣿⣯⣷⣿⣯⣿⣽⡾⣽⣳⣿⣷⣿⣿⣿⡿⣽⣿⡘⢶⡱⢪⡱⢈⡞⢤⡑⢎⢳⣯⢞⡽⣳⣽⡘⣧⣟⡿⢮⣑⠣⣜⣧⠒⣌⢚⡟⡜⡳⣍⠮⣵⢯⠛⡄⢣⡍⠖⣍⠲⣍⠺⡴⣹⣿⡿⣽⢯⡷⣟⠼⣌⠳⣎⢎⡳⣌⠻⣌⠷⣯⣇⠯⡵⣿⣽⣿⣿⣏⣿⢾⣹
⣿⣿⣿⣿⣿⣿⣿⣟⣾⣟⣳⣿⣿⣿⣿⣿⡿⣏⣶⡿⣟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣽⣷⣿⡿⣷⣻⣽⣿⣿⣿⣿⣳⣿⢜⣣⢍⡳⣌⠧⡘⢦⡙⢆⠣⢞⠯⡜⢳⢎⡳⢻⣽⣿⣳⢌⢣⠽⣾⡑⢆⣊⠧⣙⠲⣬⢳⣧⡟⡱⣘⢣⡜⢭⡸⡱⢎⡳⣱⢹⣿⣿⢯⣟⡷⣏⠞⣬⢓⣎⢮⡱⢎⡽⢬⣳⢣⣟⣮⡵⣹⢾⣿⣿⣿⣞⣻⡼
⣿⣿⣿⣿⣿⣟⣷⣿⢿⣼⣿⣿⣿⣿⣿⡿⣱⣿⣻⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣽⣻⣿⣿⣿⡷⣗⣿⢎⡾⣌⠳⣌⡳⢥⠒⡍⢎⡱⢎⠲⣉⠣⢎⡱⡹⣿⣿⣿⣎⡜⡜⢶⣍⠲⣌⡗⣈⠖⡹⢿⠳⡏⢴⠱⣊⡜⢦⡓⡝⢮⡱⢣⢻⣿⣿⣻⠾⣝⡮⣙⢦⢫⡜⣶⡹⣝⣾⣳⣽⣻⣞⣷⡿⣶⡻⣿⣿⣿⡯⣗⣻
⣿⣿⣿⣿⢿⣿⣿⢫⣿⣿⣿⣿⣿⣿⣳⡿⣯⢷⣿⣻⣯⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣿⡷⣿⣽⣿⣿⣿⣻⣏⣿⢎⡷⢪⡝⣲⠝⣎⢧⢹⡘⡴⢋⡕⢪⡱⢆⠦⣑⠹⣿⣿⠆⠳⣌⢻⣜⠢⡝⡏⣔⢫⡱⢎⡽⣘⠎⡵⢣⠞⣥⡛⣜⣣⢝⡣⢿⣟⣿⣳⢿⣹⢶⣙⢮⣳⣽⣾⣽⣿⣿⣿⣿⣿⣿⣿⣿⢿⣽⣻⢿⣿⣿⣽⣳
⣿⣿⣿⣽⣿⡟⣎⣿⣿⣿⣿⣿⣿⣿⣏⡷⣯⣿⣾⢿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⡿⣿⣿⣿⡟⣧⣿⣿⣿⣯⣷⢏⣿⢎⣞⣳⡜⣱⣛⢮⡳⢦⡙⢶⡩⡜⡱⡜⢬⢲⣉⠞⣿⡟⡌⢃⠆⣿⡎⡴⠳⡜⡜⢦⡙⢮⡳⣌⡻⣜⢯⡝⣶⡹⢮⠵⣎⢳⣹⣿⣹⣯⢷⣫⢞⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣳⣯⢿⣿⣿⣗⣯
⣿⣿⣿⣿⡟⣹⣧⣿⣿⣿⣿⣿⢷⣿⡧⣿⣳⢿⣯⣿⣟⣿⣿⣿⣿⣿⣿⣯⣿⣿⣿⣿⣿⣿⣿⣿⣿⡯⣽⣿⣿⣳⣟⡾⣡⣿⢎⡼⣿⢷⢣⢭⡳⣏⣷⣙⣎⢷⣭⡱⢎⡣⢇⡞⠼⣱⣋⡜⢦⣛⡯⢗⣝⣣⠝⣎⡳⣍⡟⣴⢫⢷⣹⢮⣝⡶⣝⢯⡓⣎⠳⣞⣯⡟⣿⣯⢞⡇⣿⣿⣿⣿⣿⣯⣿⣟⣿⣽⣿⣿⣿⣿⢿⣳⣯⣟⣎⣿⣿⣾
⣿⣿⣿⡽⣼⣿⢲⣿⣿⣿⣿⣿⣿⣿⡗⣯⣟⣯⢿⣾⢿⣻⣿⣾⣿⣻⣿⣽⣿⣿⣿⣿⣿⣟⣿⣿⢿⢧⣿⣿⣳⢟⣾⡃⢷⣟⠆⣿⡽⣏⣞⢦⡓⣝⢺⣗⣮⣛⣾⣳⡭⢞⡱⢮⡹⣱⢧⢺⡱⣎⠿⣜⡞⣬⢻⡜⢧⣿⣝⣮⢟⣞⣧⡟⣮⢳⡝⢎⣱⣎⣿⡾⣽⣻⡽⣿⢮⡽⢺⣿⣿⣿⣿⣿⡷⣿⣟⣿⣾⣿⣿⡿⣟⣿⢾⡽⣾⣹⣿⣿
⣿⡿⣾⢱⣿⣿⣹⣿⣿⣿⡿⣾⣿⣿⣛⢷⡽⣞⣿⣽⣿⣿⣿⣳⣿⣻⣿⣽⣿⣿⣿⣿⣽⣿⣿⣿⣿⣺⣿⢷⣛⡾⣧⠙⣾⢿⡘⣼⢿⣽⣞⣯⢷⣎⣧⡜⠮⣟⣾⢿⣿⣭⣛⢶⡹⣭⣏⢷⡳⣭⢟⡼⣝⣮⢳⣏⣿⣾⡽⣞⡿⣚⡾⣹⢣⣳⣼⣯⣷⣿⣿⡇⣿⣳⡽⣻⣿⢼⡹⣿⣿⣿⣿⣾⣿⣽⣻⢾⣻⣿⣿⣿⣿⣟⣯⣟⢾⣽⣿⣿
⣿⣻⢧⣿⣿⡿⣼⣿⣯⣿⣿⣿⣿⡷⡽⣎⣽⣻⢾⣽⣾⣿⣟⣷⣏⢷⣟⣿⣾⢿⣟⣿⣿⣻⣾⢿⣲⣿⢯⢯⣗⡿⢢⢋⣿⢯⡒⣽⣻⣟⣾⣽⢻⣞⣷⣿⣷⣬⣝⣻⢿⣿⣟⣮⢷⡽⣮⣳⡽⢮⣟⡾⣽⣚⣯⣾⣿⣷⢿⣯⠟⣍⣣⣷⣿⣿⣿⣻⣿⣿⣟⡧⢹⡗⣯⢻⣿⣧⢇⣻⣿⣯⣷⣿⣻⢾⣽⣻⣿⢿⣿⣷⣿⣻⣞⡾⣏⢾⣿⣿
⣿⣏⣾⣿⣿⡟⣷⣿⣟⣯⣿⣿⣿⢳⣽⡳⡜⣯⢿⣽⣷⣿⣿⣿⡜⢮⡽⣾⡽⣟⣯⡿⣞⡿⣽⢯⣿⣏⡟⣾⢺⡍⣇⣻⣟⠮⣱⢺⣷⣛⣾⡝⣯⠾⣽⢯⣿⣿⣿⣷⣯⣜⡻⢯⣟⣾⢷⣳⣟⡿⣾⣽⣳⣟⣾⢿⣳⠟⣫⣴⣻⣿⣿⣿⣟⣿⣿⣷⣿⣿⣻⡝⢦⢻⡽⣣⢿⣿⣏⡖⣻⣿⣽⣷⣻⢟⡾⣽⡿⣿⣿⢿⣾⢷⣯⣳⠏⣿⣿⣿
⣿⢼⣿⣿⣿⣏⡷⣿⣿⣿⣿⣿⣟⢳⢮⣟⡵⡸⢿⣽⡾⣟⣯⣿⡿⡌⣞⣳⢽⣛⠾⣝⡯⣟⣵⣿⡻⣼⣹⢞⡯⢜⣰⣿⢺⢱⢣⣟⣾⣳⣭⢿⡾⣹⢎⡿⣽⣾⢿⣻⣿⣿⣿⣿⣼⣻⢯⣷⢯⣟⣷⣯⡷⣿⢛⣫⣴⣿⣿⣿⣿⡿⣿⣟⣿⣻⣞⡿⣽⡷⣟⡿⣌⢳⡻⣽⡚⣿⣿⣷⣙⡾⣷⢯⡝⣾⣟⣿⣿⣿⣿⣿⣯⣟⣾⡱⢻⣧⢿⣿
⣟⣾⣿⣿⣿⣧⣿⣿⢯⣿⣿⣿⣏⡟⣮⡟⡖⣧⠹⣞⣿⣻⣟⣯⣿⡕⡸⢧⡻⣜⢯⡳⣝⣾⣻⠶⣝⣧⣛⢮⠕⣮⣟⢧⣋⠞⣼⣻⣞⡷⣯⢷⣏⣷⣫⣞⣷⣻⢿⣟⣿⢿⣿⣿⢿⣿⣿⣾⣿⣻⣿⣾⣿⣳⣿⣿⣿⣿⣿⡿⣟⣿⣟⣯⣷⢻⣜⡿⣯⢷⣯⢿⡽⣶⣹⢳⡟⡼⣿⣿⣮⣝⡳⣏⠞⣽⣾⣿⣿⣿⡿⣿⣳⣟⡶⣉⣿⡽⣾⣿
⣿⣿⣯⣿⣿⣧⣿⣾⣿⣿⣿⣿⡧⣟⡼⣏⡗⣯⢳⣘⡳⢯⡿⣽⢾⣽⡐⣯⢳⢎⡳⣳⡽⣯⢗⣻⡝⡶⢩⡞⣾⣻⢎⡳⣌⣻⣞⣷⣻⢾⣽⣻⣞⣷⣻⣞⡷⣯⣟⣾⡽⣯⣟⣿⡿⣯⣿⣾⣿⣿⣷⣿⣿⣿⣿⣿⣿⢯⣿⣿⡿⣿⣻⡽⣞⡿⣾⡽⣯⢷⣯⢷⣻⡵⣯⣳⣝⣳⡹⣿⣿⣮⡕⣎⢺⡽⣿⣿⣿⡿⣿⣿⡽⣞⢱⢾⣹⢿⡽⣿
⣿⣷⡿⣿⣾⣷⣻⣿⣿⣿⣿⣿⣱⣏⣿⣏⡿⣜⢧⣧⡙⢯⠽⣹⣛⣮⢳⣭⣿⢨⣳⣯⡟⣵⣫⢷⡹⣡⢻⣽⢳⠝⣪⢵⣞⣷⣻⣾⣽⡿⣞⣷⣻⣞⡷⣯⣟⡷⣛⡾⣽⣳⢾⣽⣻⣷⣻⣿⣽⣿⣿⣿⣿⣿⣻⢾⡽⣿⢿⣯⢟⡷⣯⣟⣯⣟⣷⢿⣽⣻⣞⣯⢷⣻⡵⣏⡾⣥⣳⠹⣾⣟⣷⡘⣼⣹⢿⣽⣷⡿⣟⣷⡛⡴⣟⢺⡽⣯⡗⣿
⣿⣯⣿⣟⣷⣯⢿⣿⣿⣿⣿⣿⢼⡧⣿⢯⡷⣹⢎⣷⣻⡡⣏⢧⡹⣜⠳⡜⢣⣾⡟⣶⢻⡜⣧⠫⣴⠳⡟⣬⢧⣟⣷⣻⣾⣿⣿⣿⣿⢿⣟⣯⣿⣽⣻⢷⣯⢿⡽⣻⡵⢯⣟⣾⣷⣧⣟⣾⣳⣛⣞⣳⢯⡗⣯⢷⣻⣽⣻⣞⣯⣟⡷⣯⣟⣾⣯⢿⡾⣷⣻⣞⣯⢷⣛⡾⣵⢫⡖⣯⢜⣻⣞⣧⢺⡵⣻⣟⡾⣽⣻⠦⣹⠵⣏⡳⣽⢷⡏⣿
⣿⣯⣷⣿⣻⣽⣻⣿⣿⣿⣿⡿⣾⡽⣿⣻⣝⢧⡻⣞⣷⣳⡙⣦⠳⣜⡹⢆⡿⢧⣟⡞⣧⢛⡴⢫⡵⣻⡼⣯⣟⡾⣷⣿⣳⣿⣿⣿⢿⣿⣿⣿⣽⣷⣿⣻⣞⣯⢿⣵⣫⢟⡾⣜⡷⣻⣿⣿⡿⣝⣮⡝⣮⢿⣽⣻⢗⣯⢶⣻⢾⣽⣻⣽⣯⢿⣾⣟⣿⣟⣷⣯⣟⣯⢿⡽⣞⡯⣽⣚⢮⡒⢿⣾⡱⢣⡟⣾⠹⣧⢇⣯⢱⡻⣇⢽⣚⣯⣏⣿
⣿⣽⣾⢿⣽⣿⣹⣿⣿⣿⣿⣟⣷⣻⣽⢿⣏⡶⣻⡽⣞⡷⣧⢻⡱⢎⡵⣻⢏⡿⠼⣙⡤⢯⡜⣷⣛⢷⣻⣳⢯⣿⣟⣾⣿⣿⣷⣿⣿⣿⣿⣿⣿⣾⣟⣷⣻⣞⢿⣮⣏⣟⠾⣝⢾⡳⢯⣿⣿⣟⣾⣽⣯⢟⡾⣭⣟⢾⣯⣟⡿⣞⣿⣳⣿⣿⣻⣾⣿⣯⣿⣾⣻⣾⢯⣟⣷⣫⣗⢯⣳⠽⣎⠷⣏⢷⡼⣡⠟⣼⢏⣖⣫⡽⣸⡚⢦⡿⣧⣿
⣿⣻⣾⣟⣷⢿⣳⣿⣿⣿⣿⣟⡾⣯⢿⣻⣧⢷⣹⡽⣯⣟⡷⣎⡝⢮⡼⠯⣏⠵⣛⣬⢛⣧⣛⡶⢯⣛⡷⣯⢿⣳⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣟⣷⢯⣟⣶⡻⣞⢯⣛⡮⣝⢯⡞⣿⢿⣿⡻⣼⢯⡽⢶⢯⣟⣶⢯⣿⣻⣟⣿⣽⣾⣿⣿⣽⣿⣿⣷⡿⣯⣿⣞⡷⣽⣞⣻⣼⢻⡼⣹⢻⣎⣧⢳⡹⣎⢯⡲⢵⣋⠧⣝⣣⢿⡷⣿
⣿⢯⣷⣟⣯⡿⣷⣻⣿⣿⣿⣯⣟⣿⣽⣻⣽⢧⣛⣾⣳⢯⣟⡷⣜⣣⣟⢃⡾⣍⢳⠬⣏⢶⡹⣞⢯⣟⡽⣯⣟⣿⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣯⣿⣞⡷⣻⢽⣚⣧⢻⡜⣧⢻⡼⣻⢾⣱⢟⣮⠽⣏⡿⣾⡽⣯⣷⡿⣿⣿⣿⣿⣿⣾⣿⣿⣿⣾⣿⣟⣷⣯⣟⡷⣯⢷⣫⣟⢾⣧⢻⣎⠷⣣⢗⡯⣲⠝⣯⢼⡙⡦⢏⣿⣏⣿
⣿⣟⣷⣯⢿⣽⣷⣻⣿⣿⣿⡷⣯⣿⡼⣷⡿⣯⡜⡷⣯⣛⡾⡙⡍⣾⡽⢸⠲⣍⢮⢳⢎⡷⣫⡽⣳⢞⡽⣷⣻⣾⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣿⣯⣷⢯⣟⣭⢷⣫⢞⣧⢻⡜⣧⡹⣽⢇⣾⡹⢮⢿⣝⣿⣳⣟⡿⣷⣿⣿⣿⣿⣾⣿⣿⣿⣿⣽⣿⣯⣿⣿⣾⣽⣻⡽⣯⣳⢯⣟⣾⢣⢿⣃⢷⡏⣞⡥⣛⢧⡗⣭⡓⣏⣾⣏⣿
⣿⢾⣳⣯⣿⣞⡷⣯⣿⣿⣿⣟⣽⡿⣽⣳⣿⣻⠼⣹⠓⡭⢰⡱⣘⣷⣻⢸⢏⡜⣎⢧⡻⣜⢧⣻⢵⣻⡽⣯⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣷⢿⣻⢾⣝⡾⣱⢯⡞⣧⢻⣔⡳⣍⢺⡵⣫⢟⡽⣞⣷⣻⣾⢿⣿⣻⣿⣯⣿⣿⣿⣿⣿⣿⣿⣿⣟⣿⣷⡿⣯⣷⣻⣗⣯⢿⣞⡷⣏⢾⡹⡞⡵⢮⢵⢫⡾⢱⡲⡹⣜⣾⣽⣻
⣿⢯⣟⣾⣳⣯⢿⣞⣿⣿⣿⣻⣞⡿⣷⢻⣾⢯⠛⡤⢛⠴⣃⠖⣱⣯⢷⡹⢎⡼⢎⡳⣝⢮⣻⡜⣯⢷⣻⢷⣻⣾⣿⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣾⣿⣽⣟⣯⣟⣮⢗⡯⣞⡵⣫⢗⢮⠵⡎⣾⣱⢯⢯⣟⡽⣞⣷⡿⣿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣿⣟⣷⣻⢮⣟⡾⢯⣟⣞⠮⣗⠯⡵⣋⢮⢷⢏⢧⢳⡙⣦⣟⣾⢿
⡿⣯⣟⣾⣳⢯⡿⣼⣿⣯⣿⢷⣫⣿⢯⡟⢩⢖⡹⢌⠳⡸⢄⠏⣼⢯⣯⢳⡹⣜⣫⢵⢫⡞⣵⢫⣯⢟⡽⣯⢿⣳⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣷⣿⣽⡾⣽⢾⣽⣚⢷⡹⣞⡵⣫⢞⡹⢶⣏⢾⣹⠾⣭⢿⣽⡾⣟⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣽⡿⣞⣯⣟⡾⣽⣻⡽⣾⣙⣧⠻⣜⠭⣞⡯⡜⣎⢧⣙⢦⣿⢾⣿
⣿⣳⣟⡾⣽⢯⣟⡾⣷⣟⣯⣿⡽⣞⢋⡜⢣⢞⡸⢌⡣⢕⡪⡑⣯⣟⣾⢳⣙⢦⢳⣎⢷⡹⣞⡽⢮⡿⣽⣻⣟⡿⣽⣾⣿⣻⣿⣿⣿⣿⣿⣿⣿⣽⡿⣾⢷⣟⣯⣟⡶⣏⣯⡳⣝⡞⣵⢫⡝⣎⢞⡧⢯⣟⣽⣻⢾⣽⢿⣯⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣾⡿⣟⣿⣳⣯⣟⣧⢿⡽⣶⣓⣎⢳⡍⣾⡽⣱⢚⡜⢦⡙⣮⢿⣯⡿
⣷⢿⣾⣹⣏⡿⣾⢷⣏⡿⣏⣷⠏⣰⠏⡸⢇⡾⡰⢏⡸⢎⢱⢱⡿⣾⢷⢹⣎⢹⡶⣎⢷⡹⣎⡹⣷⢏⣷⢿⣾⣹⣿⣹⡿⣿⣿⢿⣹⣿⣿⡿⣾⣿⣹⡿⣿⡾⣷⣏⣹⡏⣶⢿⣈⢿⡸⣇⡾⣈⡏⣾⢹⡾⣾⣹⢿⡾⣿⣹⣾⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣿⣹⣷⢿⣾⣹⢾⣹⢷⣇⡎⢷⡸⣷⢁⡇⣏⡸⢇⡹⣸⡿⣾⠷
⣯⣟⣾⢳⣯⣻⡽⣎⣿⣻⡽⢣⠞⣥⢫⡕⣣⠖⡝⢮⡱⣋⢮⡱⣻⣭⢿⡌⣟⢦⣛⣬⠳⣝⢮⡳⣽⢺⡽⣞⣳⣟⡾⣽⣟⣿⣽⡿⣿⣯⣷⡿⣟⡷⣿⣽⣳⣟⡷⣽⣣⢟⡭⣗⢫⢎⡷⡹⢎⢷⣚⢧⡟⡾⣵⢫⡾⣽⢷⡿⣽⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣿⣟⣷⡿⣽⣻⢾⡽⣞⣯⣟⡮⡜⢢⡹⠇⡜⡰⢡⢛⡬⢳⣱⢿⣏⢳
⣷⣻⡞⣟⡾⣵⣻⡽⣞⠷⣡⢏⡞⡴⢣⡞⣥⡛⣼⢣⢳⡍⣶⠱⣟⡾⣻⢤⢻⡮⡕⣎⢳⡝⣮⢳⡭⣗⢯⣽⢳⣯⢿⡽⣾⡽⣞⣿⡽⣷⢯⣟⣯⣟⣳⢯⣷⢻⣞⢧⡟⣮⢗⣮⢛⡞⣶⢹⡹⢆⣛⢮⣝⣳⡭⣷⣻⡽⣯⢿⣟⣾⣿⣿⣾⣿⣽⣿⢿⣿⢿⣻⣷⣿⢯⣿⢯⡿⣽⢯⣟⠾⣽⣞⣳⠇⣍⠳⣔⢣⠘⡔⠣⡜⢨⢇⣿⡿⣌⠧
⡷⣯⡽⣯⣽⡳⣏⢷⢋⠶⡱⢮⡜⡵⢫⡜⡶⣹⣒⢯⣓⢾⣡⠟⣽⣷⣻⢎⡜⣷⡹⣬⡓⡾⣱⢏⡾⣹⢞⡮⣟⡼⢯⣽⣳⢿⣽⣳⡿⣽⣻⣞⢷⣫⡽⣏⣾⢻⣼⢫⣞⡵⣫⢞⡹⡞⣥⠯⣽⢸⣹⢺⡜⣧⢻⣼⣳⠿⣽⢯⣟⡿⣾⣷⢿⣯⣿⣻⣿⣻⡿⣟⣿⡾⣟⣯⡿⣽⢯⣟⣞⣻⢳⡯⣽⡘⡴⢩⢆⣋⢖⡨⠱⠌⡥⢾⣯⠳⣌⢳
⣟⡷⣻⣵⡳⣿⣹⠎⡸⣇⣛⢦⡝⣞⣣⢟⡱⢧⣏⠾⣭⠶⣭⢻⡼⣿⣯⡇⢾⡰⣟⣦⢹⡱⢧⣛⡼⢣⡟⣼⣭⢻⡽⣲⢟⣮⢗⣯⢿⣳⢟⣞⣯⢳⣝⢮⡗⣯⢞⡳⣎⢷⡹⢎⡷⣹⡒⣟⠆⣸⢎⡷⣹⢎⡟⡶⣝⣻⣽⣻⣞⣿⣳⢿⣯⢷⣟⡷⣯⣷⡿⣟⣯⣿⣻⢷⣻⣽⣛⡾⣎⠷⣯⢽⠆⣧⠓⡭⢎⡼⢌⡣⢇⠹⣼⢿⡙⢢⢍⠲
⣯⣽⣳⡳⣟⣵⠫⣰⢇⡯⣜⡞⣼⡱⣎⢯⣝⡳⣎⠿⣜⣻⡼⢧⣳⢻⣿⣽⢪⣵⠸⣧⢧⡹⢖⣣⡝⣧⣛⠶⣭⢳⡝⣧⡻⣜⢯⡞⣧⢟⡾⣹⢎⡷⢮⣳⢻⡜⣯⢳⡝⣮⡝⣪⢵⢣⣻⠼⡱⢌⡻⣴⢫⡞⣽⢳⣝⣳⢮⣗⣻⢾⣽⣻⣞⠿⣾⣽⣳⢯⣟⡿⣽⢾⣽⣫⢷⣏⢷⡻⣼⢻⣜⡏⡞⡴⢫⡜⣣⢎⢧⡹⣌⢳⢫⡟⠨⣅⠪⣱
⣷⡳⣽⢽⣹⡞⢡⡳⢎⡷⣚⡼⣥⢻⣜⡳⣎⣷⡹⣏⣯⠷⣽⣫⢷⡭⣿⣟⡦⢯⣛⡬⢷⡙⢮⡱⢞⡱⣎⡻⣜⢧⣛⢶⡹⣝⢮⡝⣮⢻⡜⣧⢯⡝⣧⢏⡷⣹⢎⡷⡹⢦⡝⢦⣛⢮⢇⢣⡱⢎⡱⢧⣛⡼⢣⡟⣼⢣⠿⣜⣯⣞⠷⣧⣻⣛⢷⣺⡽⣻⢾⡽⣏⣿⢲⢯⣳⢞⣯⢳⣭⢳⡞⡸⡵⢭⣓⢮⡕⢮⡲⡕⣎⢧⠳⡌⡱⢄⡓⣼
⣿⡽⣞⢯⣳⠍⣳⢭⣛⡼⣣⠷⣭⢳⡞⣽⢳⣎⣿⣹⢞⣻⣳⡽⣯⢾⡱⣿⡷⣹⣭⢟⣦⢻⡆⢏⡳⣹⡜⡵⣫⠞⣭⠞⣵⢫⡞⡽⢎⡷⣹⢎⡷⣹⢮⡝⢶⣹⠺⣜⡝⣮⢹⢧⡏⢏⡜⢦⢣⢏⡜⢳⢧⣚⠧⣝⠮⣝⡿⣹⠶⣭⢟⣞⡳⢯⣛⣶⢻⡭⢷⣫⢗⡞⣯⢳⡝⡾⣜⡳⢮⠟⣴⢯⡝⣧⢏⡶⣹⢣⡗⣹⠜⣎⣳⢱⡂⠎⢴⣻
⠿⣿⡭⣷⢫⣘⢧⣏⢞⡶⣭⢻⣜⢷⣫⢯⡷⣛⡶⣯⣟⡷⣯⣟⡷⣯⣗⢯⣷⣣⢻⡾⣭⢷⣫⢧⡑⢧⣚⡵⡹⡞⣥⠻⣜⢧⣛⡼⢫⡜⣧⢻⡜⢧⡻⡜⣧⢓⡻⡜⣼⢡⡟⣾⡘⢮⢜⡣⢇⡞⡼⣈⠳⣭⠞⣥⣛⣮⢳⣭⠻⡜⢾⡼⣹⢏⡾⣍⢷⡹⣏⢾⡹⣞⡵⣫⢞⡵⢫⡽⢋⣾⣳⣞⢾⣱⢯⡞⣵⢫⡞⣥⢻⡜⢦⡳⢭⡜⢲⡿
⣟⠽⣷⣫⠇⣞⢧⡞⣽⢺⡵⣛⣮⢟⡼⣯⡽⣯⣟⡷⣯⣟⡷⣯⣟⣷⣻⣶⢫⣗⢯⣻⣽⣳⢯⠾⣝⡎⠳⣼⢱⡏⣖⠻⡜⣎⢶⡙⣧⢻⡴⣋⢾⡹⢧⡝⣲⢫⠵⡹⢆⠣⣜⢣⡜⢣⢮⢱⣃⢮⡱⢎⡱⢌⠻⣖⡿⣼⢳⢮⣟⠼⣓⠾⣱⢏⡾⣙⢮⠵⣏⢾⡱⣎⠷⣙⢮⡝⣫⡴⣟⣾⣳⣞⣯⠷⣏⡾⣭⢷⡹⣎⢷⡚⡧⡝⣦⠹⣌⠷
⣏⢯⡽⣿⣘⢮⡳⣝⢮⣳⠽⣝⣮⠿⣽⣳⣟⡷⣯⣟⣷⣯⢿⣷⣻⣾⣽⣞⣯⡞⡗⣮⠷⣯⣟⣻⢧⣏⡗⡤⣋⠼⣎⢳⡹⣜⢲⡙⡶⣻⢶⡹⢎⣝⢣⠞⣥⠋⣎⢱⡊⡵⢊⡖⣩⢓⢎⡆⢳⢢⡝⢬⡱⢎⠖⣸⣿⣯⣿⣻⣮⠹⡼⣩⠗⣎⡳⡝⣮⢳⡜⢣⣟⡼⣣⠟⣬⣞⣵⣫⣿⣳⣟⣾⣽⣻⡽⣯⢷⣫⠷⣝⡮⣽⡱⣛⡴⣛⠼⣆
⣻⢎⡷⣃⢯⡞⣵⢫⡾⣱⠿⣽⣺⢟⣷⣻⢾⣽⣳⡿⣾⣽⡿⣞⣿⢾⣳⡿⣯⢿⡽⣎⣻⢳⣯⡽⣞⣮⡝⡶⣩⠞⡹⢆⡱⢌⢢⡙⢲⢹⠧⡙⠎⡜⠤⢣⡔⣩⢆⡳⢜⡡⢏⡜⡱⢎⢲⡽⣎⠶⢮⡱⣘⢎⡝⣆⠻⢿⡻⠟⢢⢛⡴⢋⡞⣥⢳⣙⣾⢣⠝⠣⠜⢳⣟⣾⡟⣞⣶⢿⣳⣯⣿⣞⣷⣯⢿⡽⣯⢯⣿⣹⢞⡵⣫⢵⡳⡭⣞⡹
⢯⡞⣵⣸⢳⡞⣵⣫⢗⣯⢟⣳⢯⣟⡾⣽⣻⣞⣯⣿⣟⣷⣿⣿⣻⣿⣟⣿⣿⣻⣟⣾⡱⣏⡾⣽⣳⢧⡟⣵⢣⢏⡵⢋⡖⢣⢆⢧⠣⡜⢢⡉⢼⡓⣎⠳⣜⡱⢎⡵⢪⡕⣫⠜⡵⢫⡞⡽⣸⡙⡮⣕⢫⠞⡼⣌⡛⢦⠳⣍⠧⢦⢌⡱⠌⡔⢣⠜⡎⡔⢊⡱⣎⢷⣿⢳⡽⣾⣟⣿⡿⣽⣾⢿⣽⣾⣿⣻⣽⣻⢾⣭⣟⡾⣵⣫⢷⡹⣖⡹
⣻⢼⢣⡳⣝⢾⡱⢯⡾⣭⢿⣽⣻⢾⣽⣻⡷⣟⣯⣷⣿⢿⣷⡿⣿⣽⡿⣿⣾⢿⣽⡷⣿⣭⣳⣏⠷⣯⣛⣮⢳⣎⡜⣣⢞⡱⢎⠮⡱⣌⠧⡜⢦⡹⣌⢳⣌⠳⣍⢞⡱⢎⡵⢫⠵⣫⢳⡱⢣⣝⠲⡝⢮⣙⠶⣡⢛⡬⣓⢎⡟⣬⢚⡴⢋⡜⣆⠩⢔⢢⢏⡵⣽⢟⣼⣳⣿⣟⣿⣽⣿⣟⣿⣿⢿⣷⣿⣻⣯⡿⣟⣾⡽⣞⣷⣹⣎⠷⣭⢳
⣧⢻⢸⡳⣝⢮⡽⣳⣏⣯⣟⡾⣽⣻⢾⡷⣿⣿⣻⣯⣿⣿⣿⣿⣿⣿⣿⣿⣯⣿⡿⣽⡿⣞⣷⣞⠿⣧⣻⢼⡳⢮⡜⡱⢎⡵⣊⠷⣑⠮⣱⡙⢦⠳⣌⡳⣌⠗⣎⠮⣕⢫⣜⢣⡛⡴⢣⡝⣣⠮⣝⡹⢦⡙⢮⡱⣋⠶⣩⢎⡷⣌⠳⣜⢣⠞⡬⠹⣌⡷⣫⡽⣣⣿⢾⣻⣽⣾⢿⣻⣾⣿⣿⣿⣿⣿⣷⣿⡿⣽⣿⡷⣿⡽⣞⡷⣞⣻⣜⣳
⣞⠭⣏⢷⡹⣎⡷⣻⣼⢳⣯⣟⡷⣿⣻⣟⣿⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⡿⣿⡿⣽⣟⡾⣽⣻⢧⡟⣮⢽⣣⢏⡵⣋⠶⣩⠞⣌⢧⡱⢎⢣⡛⠴⣓⢬⡛⣬⢓⣎⠳⣬⢣⡝⡖⣭⢚⡥⣛⠴⣙⢦⣋⢧⢓⡭⣚⢥⣺⠵⣌⠳⣌⢣⠞⣰⣛⡬⢷⣭⢷⡿⣽⣻⣯⣿⣟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⢯⣿⣽⣻⡽⣖⢯⢶
⡞⣝⢯⡞⡵⣏⣾⢳⣭⣟⡾⣽⣻⢷⡿⣯⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣿⣟⣾⣟⡷⣯⢟⣾⡹⣎⢷⣋⠶⣩⠞⣥⢛⡬⢲⢱⡊⣕⢪⠓⡭⢲⡙⡴⣋⡜⡳⣌⠳⣜⣣⠜⣣⠞⣡⢛⡜⣆⡓⣎⢣⠞⣡⠞⣜⠣⣌⠳⣌⠳⢎⡵⣣⢟⡽⣮⢿⣽⣳⣟⣷⢿⣻⣯⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣾⣿⣻⣞⣷⣻⡽⣞⢯
⣽⢸⢧⡻⣝⠾⣼⣛⣮⢿⣽⣳⢿⣻⣿⢿⣽⣿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣿⢿⣾⣻⢾⡽⣯⢟⣶⢻⡝⣮⢭⡳⢥⡛⡴⣋⡜⣣⠇⡞⢤⢣⡙⣌⠓⠬⠱⠜⡲⣑⢎⠳⡌⣷⡩⢆⡝⣢⢃⡞⣤⠳⡜⠦⢛⢠⠻⣝⠲⣌⠳⣌⢻⣜⡳⣝⢾⡹⣧⣟⢾⣳⣟⡾⣿⣻⣽⣿⣻⣽⣿⣿⣿⣿⣿⣿⣿⣿⣯⣷⣿⢿⣽⣾⣳⢿⣹⣞
⣞⢸⢧⡻⣜⣻⡵⣻⣞⢿⡾⣽⣻⣯⣿⢿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣿⢯⣟⣯⢿⣝⣻⡼⣳⢻⡜⣧⣛⢦⡙⢶⡱⢎⡕⡫⢜⠣⠖⡉⣄⠚⠬⣑⠲⡐⠤⡊⢍⡩⡙⡍⣋⠜⡩⢍⡩⠔⠣⠜⣐⠣⢢⠱⢠⠒⡌⠱⢎⡳⢎⡷⣹⢎⡷⣳⢞⣯⢷⣯⢿⡽⣟⣯⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣿⣻⡾⣽⢯⡷⣞
--]===========================================================]
" > "$temp_file"
              cat "$file" >> "$temp_file"
              mv "$temp_file" "$file"
            fi
          done < <(find . -type f)
          
          echo "Processed $found_files files."
